apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-ada-postgresql
  namespace: team-ada-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: team-ada-postgresql
  data:
  - secretKey: postgres-password
    remoteRef:
      key: team-ada-akkoma-staging-postgresql
      property: postgres-password
