apiVersion: ee.kargo.akuity.io/v1alpha1
kind: MessageChannel
metadata:
  name: demo-snow-smtp
  namespace: demo-snow
spec:
  secretRef:
    name: smtp-credentials
  smtp:
    from: emily.chen@akuity.io
    host: smtp.gmail.com
    insecureSkipVerify: false
    port: 587
    to:
      - emily.chen@akuity.io
    useTLS: true
