apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: demo-ephemeral
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: demo-ephemeral
  namespace: demo-ephemeral
spec:
  promotionPolicies:
  - stageSelector:
      name: "regex:preview.*"
    autoPromotionEnabled: true
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
