apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: team-eddie
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: team-eddie
  namespace: team-eddie
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true