apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: red
  name: dev
  namespace: team-eddie
spec:
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: ${{ vars.sourceBranch }}
                path: ${{ vars.path_src }}
            repoURL: ${{ vars.gitRepo }}
          uses: git-clone
        - uses: yaml-update
          config:
            path: ./src/akuity.yaml
            updates:
            - key: value
              value: ${{ ctx.promotion }}
        # - uses: http
        #   config:
        #     method: POST
        #     url: https://api.github.com/repos/eddiewebb/circleci-samples/git/trees
        #     headers:
        #     - name: Authorization
        #       value: Bearer ${{ secret('app-jwt').jwt }}
        #     - name: Accept
        #       value: "application/vnd.github+json"
        #     - name: X-GitHub-Api-Version
        #       value: "2022-11-28"
        #     body: |
        #       ${{ quote({
        #         "base_tree":"9fb037999f264ba9a7fc6274d15fa3ae2ab98312"
        #         "tree":[
        #           {"path":"file.rb",
        #           "type":"blob",
        #           "sha":"44b4fc6d56897b048c772eb4087f854f46256132"}
        #           ]
        #         }) }}
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.path_src }}
            message: "Writecommitfor ${{ ctx.promotion }}"
            author:
              #your-app-name[bot]
              name: akuity-signing-demo[bot]
              #your-app's USER -id+your-app-name[bot]@users.noreply.github.com
              #JSON Schema email format does not support the brackets [] used by Github :(
              email: "261204081+akuity-signing-demo-bot@users.noreply.github.com"
        - uses: git-push
          as: push
          config:
            path: ${{ vars.path_src }}
      vars:
        - name: gitRepo
          value: https://github.com/eddiewebb/circleci-samples
        - name: sourceBranch
          value: main
        - name: path_src
          value: ./src
  requestedFreight:
    - origin:
        kind: Warehouse
        name: team-eddie
      sources:
        direct: true

