
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx
    revision: release-1.13
    path: deploy/static/provider/cloud
  destination:
      server: http://cluster-eddie-local:8001
      namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
