apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: functional-tests
  namespace: team-eddie
spec:  
  args:
  - name: test-image
    value: alpine:latest
  metrics:
    - name: functional-tests
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - /run-tests.sh
                    args:
                      - '{{ args.test-image }}'
                    image: {{ args.test-image }}
                    name: test
                restartPolicy: Never