apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: functional-tests
  namespace: team-eddie
spec:  
  args:
  - name: test-image-tag
    value: alpine:latest
  - name: test-image-fail
    value: "pass"
  metrics:
    - name: functional-tests
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - /run-tests.sh
                    args:
                      # this is purely demo candy, allows us to print the version in output. 
                      - '{{ args.test-image-tag }}'
                      - '{{ args.test-image-fail }}'
                    # this is the part that matters, we're changing the _actual_ image used.
                    image: "ghcr.io/akuity/sedemo-monorepo-rollouts-app-test:{{ args.test-image-tag }}"
                    name: test
                    imagePullPolicy: Always 
                restartPolicy: Never