apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: team-eddie
data:
  appImageUrl: ghcr.io/akuity/sedemo-monorepo-active-active
  testImageUrl: ghcr.io/akuity/sedemo-monorepo-active-active-test
  gitRepoUrl: https://github.com/akuity/sedemo-monorepo