apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: repo-credentials
spec:
  capabilities: 
  - access-credentials
  ## REQUIRED: image to execute the command in
  image: badouralix/curl-jq
  ## REQUIRED: command to run
  command: 
    - sh
    - "-c"
    - |
      #echo "STEP_DIRECTORY: $STEP_DIRECTORY"
      #echo "CREDENTIALS_SERVER_HOST: $CREDENTIALS_SERVER_HOST"
      BOOTSTRAP=$(cat "$STEP_DIRECTORY/credentials/token" | base64 -d)
      EXCHANGE_RESPONSE=$(curl -s -X POST "$CREDENTIALS_SERVER_HOST/tokens/exchange" \
        -H "Authorization: Bearer $BOOTSTRAP")
      echo "EXCHANGE_RESPONSE: $EXCHANGE_RESPONSE"
      SESSION=$(echo "$EXCHANGE_RESPONSE" | jq -r .token)
      echo "SESSION: $SESSION"
      curl -sf -X POST "$CREDENTIALS_SERVER_HOST/credentials" \
        -H "Authorization: Bearer $SESSION" \
        -H "Content-Type: application/json" \
        -d '{
          "namespace": "'"$PROJECT"'",
          "credType": "git",
          "repoURL": "https://github.com/akuity/sedemo-monorepo"
        }'
## OPTIONAL: output capture configuration
  output:
    source:
## One of Pipe | Stdout | Stderr | File, default is Pipe
      type: Pipe
## required when type is File, should be omitted if it's not
      path: ""
## One of JSON | YAML | KeyValue | Text
## inferred from file extension when omitted, default is KeyValue
      format: Text
## Apply expressions to output to reformat with different keys
## If omitted returns the parsed output as is
    # transform:
    #   warning: output.failure_count > 5
    #   status: output.status
    #   failure_count: output.failure_count
     # message: output.hello
## OPTIONAL: error handling metadata
  defaultTimeout: 5m
  defaultErrorThreshold: 3
## OPTIONAL: container resources configuration
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "128Mi"
      cpu: "25m"
