apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: team-eddie
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: team-eddie
  namespace: team-eddie
spec:
  promotionPolicies:
  - stageSelector:
      name: "regex:.*-primary"
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:.*-secondary"
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:validate-environment-dev"
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:summarize-deployment-.*"
    autoPromotionEnabled: true