---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qa-team
  namespace: team-eddie
  annotations:
    kargo.akuity.io/description: Promote to Staging only
    # the group/team/role from IdP goes here.
    rbac.kargo.akuity.io/claims: '{"groups":["sedemo-qa"]}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-team
  namespace: team-eddie
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - promotions
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - kargo.akuity.io
  resources:
  - 'stages'
  verbs:
  - promote
  # Limit promotions to a subset of Stages
  resourceNames:
  - 'staging'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-team
  namespace: team-eddie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qa-team
subjects:
- kind: ServiceAccount
  name: qa-team
  namespace: team-eddie
---
# This RoleBinding allows the qa-team ServiceAccount to view project
# resources (without redefining read rules), by binding it to the
# built-in kargo-viewer Role.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-team-viewer
  namespace: team-eddie
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-viewer
subjects:
- kind: ServiceAccount
  name: qa-team
  namespace: team-eddie