apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-primary
  namespace: team-eddie
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: application-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      - name: path_info
        value: ./info
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-rollouts-app
      steps:
      # use http step to pull https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
      # Alternately authorative file could be cloned from git, and then parsed with yaml-parse step 
      - uses: http
        as: find-primary
        config:
          url: https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
          method: GET
          outputs:
          - name: primaryCluster
            fromExpression: response.body.dev.primary.cluster
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ${{ vars.path_src }}
          - branch: env-eddie/dev/${{ outputs['find-primary'].primaryCluster }}
            create: true
            path: ${{ vars.path_out }}
      - uses: git-clear
        config:
          path: ${{ vars.path_out }}
      # use output in helm template step to generate k8s manifests for promotion
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/rollouts-app/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/rollouts-app/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/${{ outputs['find-primary'].primaryCluster }}/manifests
          namespace: team-eddie-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: destinationCluster
              value: ${{ outputs['find-primary'].primaryCluster }}
          outLayout: flat
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.path_out }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_out }}
          targetBranch: env-eddie/dev/${{ outputs['find-primary'].primaryCluster }}
      # Now two conditional argocd-update steps to deploy the primary, using a conditional if
      - uses: argocd-update
        as: deploy-cluster-a
        if: ${{ outputs['find-primary'].primaryCluster  == "sedemo-primary" }}
        config:
          apps:
          - name: team-eddie-dev-sedemo-primary
      - uses: argocd-update
        as: deploy-cluster-b
        if: ${{ outputs['find-primary'].primaryCluster  == "sedemo-secondary" }}
        config:
          apps:
          - name: team-eddie-dev-sedemo-secondary
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-secondary
  namespace: team-eddie
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: application-a
    sources:
      stages:
      - dev-primary
      requiredSoakTime: 1m0s
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      - name: path_info
        value: ./info
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-rollouts-app
      steps:
      # use http step to pull https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
      - uses: http
        as: find-secondary
        config:
          url: https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
          method: GET
          outputs:
          - name: secondaryCluster
            fromExpression: response.body.dev.secondary.cluster
      #
      # Alternately authorative file could be cloned from git, and then parsed with yaml-parse step to get current primary
      #
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ${{ vars.path_src }}
          - branch: env-eddie/dev/${{ outputs['find-secondary'].secondaryCluster }}
            create: true
            path: ${{ vars.path_out }}
      - uses: git-clear
        config:
          path: ${{ vars.path_out }}
      # use output in helm template step to generate k8s manifests for promotion
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/rollouts-app/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/rollouts-app/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/${{ outputs['find-secondary'].secondaryCluster }}/manifests
          namespace: team-eddie-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: destinationCluster
              value: ${{ outputs['find-secondary'].secondaryCluster }}
          outLayout: flat
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.path_out }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_out }}
          targetBranch: env-eddie/dev/${{ outputs['find-secondary'].secondaryCluster }}
      # Now two conditional argocd-update steps to deploy the secondary, using a conditional if
      - uses: argocd-update
        as: deploy-cluster-a
        if: ${{ outputs['find-secondary'].secondaryCluster  == "sedemo-primary" }}
        config:
          apps:
          - name: team-eddie-dev-sedemo-primary
      - uses: argocd-update
        as: deploy-cluster-b
        if: ${{ outputs['find-secondary'].secondaryCluster  == "sedemo-secondary" }}
        config:
          apps:
          - name: team-eddie-dev-sedemo-secondary
