apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: team-eddie
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-pod-identity
    sources:
      direct: true
  # verification:
  #   analysisTemplates:
  #     - name: integration-test
  #       kind: ClusterAnalysisTemplate
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: targetBranch
        value: env-eddie/dev 
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitRepo }}
        checkout:
        - branch: ${{ vars.sourceBranch }}
          path: ${{ vars.path_src }}
        - branch: ${{ vars.targetBranch }}
          create: true
          path: ${{ vars.path_out }}
    - uses: git-clear
      config:
        path: ${{ vars.path_out }}
