apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-primary
  namespace: team-eddie
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: application-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      - name: path_info
        value: ./info
      steps:
      # use http step to pull https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
      - uses: http
        config:
          url: https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
          method: GET
          outputPath: ${{ vars.path_info }}/environments.yaml
      # load current primary destination cluster using yaml parse step
      - uses: yaml-parse
        as: find-primary
        config:   
          path: ${{ vars.path_info }}/environments.yaml  
          outputs:
          - name: currentPrimary
            fromExpression: dev.primary.cluster
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ${{ vars.path_src }}
          - branch: env-eddie/dev/${{ find-primary.outputs.currentPrimary }}
            create: true
            path: ${{ vars.path_out }}
      - uses: git-clear
        config:
          path: ${{ vars.path_out }}
      # use output in helm template step to generate k8s manifests for promotion
      - uses: helm-template
        config:
          path: ${{ vars.path_src }}/deploy/chart
          outPath: ${{ vars.path_out }}/${{ find-primary.outputs.currentPrimary }}/manifests
          outLayout: flat
          namespace: team-eddie-dev
          setValues:
            key: destinationCluster
            value: ${{ find-primary.outputs.currentPrimary }}
      # Now two conditional argocd-update steps to deploy the primary, using a conditional if
      - uses: argocd-update
        as: deploy-cluster-a
        if: ${{ find-primary.outputs.currentPrimary }} == "sedemo-primary"
        config:
          apps:
          - name: team-eddie-dev-sedemo-primary
      - uses: argocd-update
        as: deploy-cluster-b
        if: ${{ find-primary.outputs.currentPrimary }} == "sedemo-secondary"
        config:
          apps:
          - name: team-eddie-dev-sedemo-secondary
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-secondary
  namespace: team-eddie
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: application-a
    sources:
      stages:
      - dev-primary
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      - name: path_info
        value: ./info
      steps:
      # use http step to pull https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
      - uses: http
        config:
          url: https://demo-public-notsecure.s3.us-east-1.amazonaws.com/environments.yaml
          method: GET
          outputPath: ${{ vars.path_info }}/environments.yaml
      # load current primary destination cluster using yaml parse step
      - uses: yaml-parse
        as: find-secondary
        config:   
          path: ${{ vars.path_info }}/environments.yaml  
          outputs:
          - name: currentSecondary
            fromExpression: dev.secondary.cluster
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ${{ vars.path_src }}
          - branch: env-eddie/dev/${{ find-secondary.outputs.currentSecondary }}
            create: true
            path: ${{ vars.path_out }}
      - uses: git-clear
        config:
          path: ${{ vars.path_out }}
      # use output in helm template step to generate k8s manifests for promotion
      - uses: helm-template
        config:
          path: ${{ vars.path_src }}/deploy/chart
          outPath: ${{ vars.path_out }}/${{ find-secondary.outputs.currentSecondary }}/manifests
          outLayout: flat
          namespace: team-eddie-dev
          setValues:
            key: destinationCluster
            value: ${{ find-secondary.outputs.currentSecondary }}
      # Now two conditional argocd-update steps to deploy the secondary, using a conditional if
      - uses: argocd-update
        as: deploy-cluster-a
        if: ${{ find-secondary.outputs.currentSecondary }} == "sedemo-primary"
        config:
          apps:
          - name: team-eddie-dev-sedemo-primary
      - uses: argocd-update
        as: deploy-cluster-b
        if: ${{ find-secondary.outputs.currentSecondary }} == "sedemo-secondary"
        config:
          apps:
          - name: team-eddie-dev-sedemo-secondary
