apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: application-a
  namespace: team-eddie
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/akuity/sedemo-monorepo
      includePaths:
      - active-active
  - image:
      repoURL: ghcr.io/akuity/sedemo-monorepo-rollouts-app
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTags: ^\d*-[a-z]*$