apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: application-a
  namespace: team-eddie
spec:
  freightCreationCriteria:
    expression: |
      imageFrom('ghcr.io/akuity/sedemo-monorepo-active-active-test').Tag == imageFrom('ghcr.io/akuity/sedemo-monorepo-active-active').Tag
      && imageFrom('ghcr.io/akuity/sedemo-monorepo-active-active').Annotations['org.opencontainers.image.revision'] == commitFrom('https://github.com/akuity/sedemo-monorepo').ID
  subscriptions:
  - git:
      repoURL: "https://github.com/akuity/sedemo-monorepo"
      includePaths:
      - active-active
      - '.github/workflows/publish-active-active-app.yml'
  - image:
      repoURL: ghcr.io/akuity/sedemo-monorepo-active-active
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^\d*-[a-z]*$
  - image:
      repoUrl: ghcr.io/akuity/sedemo-monorepo-active-active-test
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^\d*-[a-z]*$