apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: application-a
  namespace: team-eddie
spec:
  freightCreationCriteria:
    expression: |
      imageFrom(configMap('values').testImageUrl).Tag == imageFrom(configMap('values').appImageUrl).Tag
      && imageFrom(configMap('values').appImageUrl).Annotations['org.opencontainers.image.revision'] == commitFrom(configMap('values').gitRepoUrl).ID
  subscriptions:
  - git:
      repoURL: "${{ configMap('values').gitRepoUrl }}"
      includePaths:
      - active-active
      - '.github/workflows/publish-active-active-app.yml'
  - image:
      repoURL: ${{ configMap('values').appImageUrl }}
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^\d*-[a-z]*$
  - image:
      repoUrl: ${{ configMap('values').testImageUrl }}
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^\d*-[a-z]*$