apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: templated-team-projects
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/akuity/sedemo-monorepo
        revision: main
        directories:
        - path: templated/*
  template:
    metadata:
      name: '{{.path.basename}}-appsets'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      #project: '{{.path.basename}}'
      project: templated-apps
      sources:
      #pull custom values from team managed monorepo folder
      - repoURL: https://github.com/akuity/sedemo-monorepo.git
        targetRevision: main
        ref: appValues 
      # create underlying appsets for Kargo and Argo in the Argo Control plane
      # they will in turn create kargo and argo assets.
      - targetRevision: HEAD
        repoURL: https://github.com/akuity/sedemo-platform
        path: templated-teams/project-templates/
        helm:
          valueFiles:
          - '$appValues/templated/{{.path.basename}}/platform/app-values.yaml'
          valuesObject:
            repoUrl: https://github.com/akuity/sedemo-monorepo.git
            project:
              path: templated/{{.path.basename}}
              name: 'templated-{{.path.basename}}'
            application:
              name: '{{.path.basename}}'
            isStandalone: false
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true