apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-app-staging
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: rollouts-app:staging
spec:
  project: default
  source:
    repoURL: https://github.com/eddiewebb/argodemo-rollouts-app
    # path is root since our Kargo job commits a clean and fully rendered manifest o environment branch
    path: .
    targetRevision: env/staging
  destination:
    name: eddie-local
    namespace: demo-staging
  syncPolicy:
    automated:
      prune: true
      enabled: true

