apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-emily-guestbook
  namespace: argocd
spec:
  description: Team Emily's ArgoCD project
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
