{{- if .Values.rollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: loadgen
spec:
  metrics:
  - name: load-gen
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: loadgen
                image: jordi/ab
                command: [ab,"-n20","https://{{ .Values.kargo.stage }}.{{ .Values.ingress.custom_prefix }}.{{ .Values.ingress.root_domain }}/"]
              restartPolicy: Never
          backoffLimit: 1
{{- end }}