apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: kyverno-policy-apply
spec:
  command:
    - /ko-app/kubectl-kyverno
    - apply
    - "${{ config.policy }}"
    - "--resource"
    - "${{ config.resource }}"
    - "--policy-report"
    - "--audit-warn"
  image: ghcr.io/kyverno/kyverno-cli:66a2ff7afd893222113f938252dfbcf1b5eb2397
  output:
    source:
      format: YAML
      type: Stdout
    transform:
      results: output.results
      summary: output.summary

