apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Frontend service only — this stage carries warehouse-frontend freight.
resources:
- ../../services/frontend

images:
- name: ghcr.io/dhpup/guestbook
  newTag: latest
