
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-custom-apps
  namespace: argocd
spec:
  project: kargo
  source:
    repoURL: https://github.com/akuity/sedemo-platform
    path: kargo/kargo-custom
    directory:
      recurse: true
  destination:
    name: kargo
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
