apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Kargo Pipeline Definitions
  
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the 'guestbook' namespace or any namespace starting with 'guestbook-' in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - name: 'kargo'
    namespace: '*'
    server: '*'


  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
