apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: demo-downstream
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: demo-downstream
  namespace: demo-downstream
spec:
  promotionPolicies:
  - stageSelector:
      name: "regex:dev.*"
    autoPromotionEnabled: true
  - stageSelector:
      name: prod-eu-west-customer-c
    autoPromotionEnabled: false
  - stageSelector:
      name: "regex:prod.*"
    autoPromotionEnabled: true
