
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-rollouts
    path: manifests
    directory:
      recurse: false
      include: "install.yaml"
  destination:
        server: http://cluster-eddie-local:8001
        namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
