apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: lock-it-down
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: lock-it-down
  namespace: lock-it-down
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:prod.*"
    autoPromotionEnabled: true