{{ range $key, $val := .Values.environments }}
{{ if or ( $.Values.environments.staging) (ne $key "staging") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{$.Values.application.name}}-{{$key}}'
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    akuity-labs: "true"
  annotations:

  {{ if (eq $key "dev") }}
    kargo.akuity.io/authorized-stage: '{{$.Values.application.name}}:{{$key}}'
  {{else}}
    kargo.akuity.io/authorized-stage: 'release-manager:{{$key}}'
  {{ end }}
    
spec:
  project: '{{$.Values.project.name}}'
  source:
  #pull custom values from team managed monorepo folder (rendered by Kargo)
    repoURL: '{{$.Values.repoUrl}}'
    {{ if (eq $key "dev") }}
    targetRevision: env/{{ $.Values.application.name }}-{{$key}}
    {{else}}
    targetRevision: env/{{$key}}
    {{ end }}

    {{ if (eq $key "dev") }}
    path: .
    {{else}}
    path: "{{ $.Values.application.name }}"
    {{ end }}
  destination:
    name: sedemo-primary
    namespace: {{ $.Values.application.name }}-{{$key}}
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 2
---
{{ end }}
{{ end }}