apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-daniel
  namespace: argocd
spec:
  description: Team Daniel's ArgoCD project
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
