apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: smoke-test
  namespace: active-active
spec:
  args:
  - name: environment
    value: missing-value
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                    args:
                      - 'echo "Running verification tests for {{args.environment}}.."; for i in $(seq 1 5); do echo -e "\nVerification Step $i of 5"; sleep 2; echo -e "\tPASS"; done'
                    image: alpine:latest
                    name: test
                restartPolicy: Never