apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: kyverno-policy-check
spec:
  image: ghcr.io/kyverno/kyverno-cli:66a2ff7afd893222113f938252dfbcf1b5eb2397
  command:
    - /ko-app/kyverno version
  # kyverno apply /path/to/policy.yaml --resource /path/to/resource.yaml