apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-east
  namespace: active-active
  annotations:
    kargo.akuity.io/color: red
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: environment
      value: dev-east
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      - name: path_src
        value: ./src
      - name: sourceBranch
        value: main
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ${{ vars.path_src }}
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}.ha
      - uses: git-commit
        as: commit  
        config:
          path: ${{ vars.path_src }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_src }}
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-west
  namespace: active-active
  annotations:
    kargo.akuity.io/color: red
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: environment
      value: dev-west
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      - name: path_src
        value: ./src
      - name: sourceBranch
        value: main
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ${{ vars.path_src }}
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}.ha
      - uses: git-commit
        as: commit  
        config:
          path: ${{ vars.path_src }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_src }}
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}
            namespace: argocd





---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: active-active
  annotations:
    kargo.akuity.io/color: purple
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      stages: 
        - dev-east
        - dev-west
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: environment
      value: ${{ ctx.stage }}-east
    - name: smoke-test
    args:
    - name: environment
      value: ${{ ctx.stage }}-west
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      - name: path_src
        value: ./src
      - name: sourceBranch
        value: main
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ${{ vars.path_src }}
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}-east/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}-east
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}-east.ha
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}-west/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}-west
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}-west.ha
      - uses: git-commit
        as: commit  
        config:
          path: ${{ vars.path_src }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_src }}
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}-east
            namespace: argocd
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}-west
            namespace: argocd

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: approve
  namespace: active-active
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      stages: 
        - staging
      requiredSoakTime: 1m0s
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      vars:
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      steps:
      - as: snowcreate
        config:
          credentials:
            sharedSecretName: kargo-step-snow
            type: api-token
          parameters:
            impact: "3"
            short_description: 'AA: Deploy ${{ imageFrom(vars.imageRepo).Tag }} to Prod'
            assignment_group: "Application Development"
            urgency: "3"
            implementation_plan: "See https://kargo.akpdemoapps.link/project/active-active/promotion/${{ ctx.promotion }}"
          tableName: change_request
          template:
            #templateId: 8d3380da83273210b6207e95eeaad33e # example
            type: normal
        uses: snow-create

      - as: snow-wait-for-condition
        config:
          # wait for "Implment" state
          condition: state=-1
          credentials:
            sharedSecretName: kargo-step-snow
            type: api-token
          tableName: change_request
          ticketId: ${% outputs['snowcreate'].sys_id %}
        uses: snow-wait-for-condition
      
      - uses: set-metadata
        config:
          updates:
            - kind: Stage
              name: approve
              values:
                snow-id: "${{ outputs['snowcreate'].sys_id }}"
                




---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-east
  namespace: active-active
  annotations:
    kargo.akuity.io/color: green
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      stages: 
        - approve
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: environment
      value: ${{ ctx.stage }}
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      - name: path_src
        value: ./src
      - name: sourceBranch
        value: main
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ${{ vars.path_src }}
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}.ha
      - uses: git-commit
        as: commit  
        config:
          path: ${{ vars.path_src }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_src }}
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-west
  namespace: active-active
  annotations:
    kargo.akuity.io/color: green
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      stages: 
        - prod-east
      requiredSoakTime: 2m0s
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: environment
      value: ${{ ctx.stage }}
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/akuity/sedemo-monorepo
      - name: imageRepo
        value: ghcr.io/akuity/sedemo-monorepo-active-active
      - name: path_src
        value: ./src
      - name: sourceBranch
        value: main
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: ${{ vars.sourceBranch }}
            path: ${{ vars.path_src }}
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/active-active/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/active-active/deploy/chart/values.yaml
          outPath: ${{ vars.path_src }}/active-active/deploy/targets/${{ ctx.stage }}/manifests.yaml
          namespace: active-active-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
            - key: ingress.sub_domain
              value: ${{ ctx.stage }}.ha
      - uses: git-commit
        as: commit  
        config:
          path: ${{ vars.path_src }}
          message: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} [skip ci]"
      - uses: git-push
        as: push
        config:
          path: ${{ vars.path_src }}
      - uses: argocd-update
        config:
          apps:
          - name: active-active-${{ ctx.stage }}
            namespace: argocd





---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: close
  namespace: active-active
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: active-active
    sources:
      stages: 
        - prod-west
      requiredSoakTime: 1m0s
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
      - as: snowupdate
        config:
          credentials:
            sharedSecretName: kargo-step-snow
            type: api-token
          parameters:
            state: "Close"
            work_notes: "Promotion to prod successful, moving change request to Close state."
            close_notes: "Promotion to prod successful, moving change request to Close state."
            close_code: "Successful"
          tableName: change_request
          ticketId: ${{ stageMetadata('approve')['snow-id'] }}
        uses: snow-update



