apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ .Values.projectName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.projectName }}
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:prod.*"
    autoPromotionEnabled: true