apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deprecated-apis
  namespace: argocd
spec:
  project: components
  source:
    repoURL: https://github.com/akuity/sedemo-platform.git
    targetRevision: main
    path: components/declarations/deprecated-apis
  destination:
        name: sedemo-primary
        namespace: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true



