apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: components
  sources:
  # - repoURL: https://github.com/akuity/sedemo-platform.git
  #   targetRevision: main
  #   ref: localValues 
  #   directory:
  #     recurse: true
  - chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.13.0
    helm:
      releaseName: metrics-server
  destination:
        name: sedemo-primary
        namespace: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
