apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Target namespace for the dev Application.
namespace: oci-airgap-dev

# Patch ENV label so workloads know which environment they are in.
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: dev
  target:
    kind: Deployment
    name: oci-airgap
