apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      direct: true
  # verification:
  #   analysisTemplates:
  #     - name: integration-test
  #       kind: ClusterAnalysisTemplate
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: targetBranch
        value: env/dev 
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/manifests.yaml
          namespace: demo-dev
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
      - task:
          name: push-manifests
      - uses: argocd-update
        continueOnError: true
        config:
          apps:
          - name: rollouts-app-dev
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: targetBranch
        value: env/staging
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      - uses: helm-template
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/manifests.yaml
          namespace: demo-staging
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}
            - key: ingress.root_domain
              value: akpdemoapps.link
      - task:
          name: push-manifests
        vars:
        - name: asPR
          value: "true"
        - name: targetBranch
          value: env/staging
      - uses: argocd-update
        continueOnError: true
        config:
          apps:
          - name: rollouts-app-staging
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: targetBranch
        value: env/prod
      - name: path_src
        value: ./src
      - name: path_out
        value: ./out
      steps:
      - task:
          name: prepare-workdir 
      - uses: helm-template
        vars:
        - name: region
          value: amer-east
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/manifests-${{ vars.region }}.yaml
          namespace: demo-prod-amer-east
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}-amer-east
            - key: ingress.root_domain
              value: akpdemoapps.link
      - uses: helm-template
        vars:
        - name: region
          value: amer-west
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/manifests-${{ vars.region }}.yaml
          namespace: demo-prod-amer-west
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}-amer-west
            - key: ingress.root_domain
              value: akpdemoapps.link
      - uses: helm-template
        vars:
        - name: region
          value: emea
        config:
          releaseName: deploy
          path: ${{ vars.path_src }}/deploy/chart
          valuesFiles:
          - ${{ vars.path_src }}/deploy/chart/values.yaml
          outPath: ${{ vars.path_out }}/manifests-${{ vars.region }}.yaml
          namespace: demo-prod-emea
          setValues:
            - key: image.tag
              value: ${{ imageFrom(vars.imageRepo).Tag }}
            - key: kargo.stage
              value: ${{ ctx.stage }}-emea
            - key: ingress.root_domain
              value: akpdemoapps.link
      - uses: jira
        as: create-change-ticket
        config:
          credentials:
            secretName: jira-secret
          createIssue:
            projectKey: CM
            summary: "Promote ${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }}"
            description: "Promoteing ${{ imageFrom(vars.imageRepo).RepoURL }}:${{ imageFrom(vars.imageRepo).Tag }} to ${{ ctx.stage }} environment. Promotion ID: ${{ ctx.promotion }}. Freight: ${{ ctx.targetFreight.name }}."
            issueType: Request a Change
            customFields:
              customfield_11490: Standard
            labels:
            - promotion
            - "${{ ctx.stage }}"
            - "release-${{ imageFrom(vars.imageRepo).Tag }}"
      - task:
          name: push-manifests
        vars:
        - name: targetBranch
          value: change/prod-${{ outputs['create-change-ticket'].key }}
      - uses: jira
        config:
          credentials:
            secretName: jira-secret
          waitForStatus:
            issueKey: "${{ outputs['create-change-ticket'].key }}"
            expectedStatus: "Iplementing"
      - uses: git-open-pr
        as: open-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          createTargetBranch: false
          sourceBranch: change/prod-${{ outputs['create-change-ticket'].key }}
          targetBranch: env/prod
      - uses: git-merge-pr
        config:
          repoURL: ${{ vars.gitRepo }}
          prNumber: ${{ outputs['open-pr'].pr.id }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-amer-east
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      stages:
      - prod
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: region
        value: amer-east
      steps:
      - task:
          name: prepare-workdir
        vars  :
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: copy
        config:
          inPath: ./src/manifests-${{ vars.region }}.yaml
          outPath: ./out/manifests.yaml
      - task:
          name: push-manifests
        vars:
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: argocd-update
        continueOnError: true
        config:
          apps:
          - name: rollouts-app-prod-${{ vars.region }}
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-amer-west
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      stages:
      - prod
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: region
        value: amer-west
      steps:
      - task:
          name: prepare-workdir
        vars:
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: copy
        config:
          inPath: ./src/manifests-${{ vars.region }}.yaml
          outPath: ./out/manifests.yaml
      - task:
          name: push-manifests
        vars:
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: argocd-update
        continueOnError: true
        config:
          apps:
          - name: rollouts-app-prod-${{ vars.region }}
            namespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-emea
  namespace: rollouts-app
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: rollouts-app
    sources:
      stages:
      - prod
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/eddiewebb/argodemo-rollouts-app
      - name: imageRepo
        value: ghcr.io/eddiewebb/rollouts
      - name: region
        value: emea
      steps:
      - task:
          name: prepare-workdir
        vars:
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: copy
        config:
          inPath: ./src/manifests-${{ vars.region }}.yaml
          outPath: ./out/manifests.yaml
      - task:
          name: push-manifests
        vars:
        - name: sourceBranch
          value: env/prod
        - name: targetBranch
          value: env/prod-${{ vars.region }}
      - uses: argocd-update
        continueOnError: true
        config:
          apps:
          - name: rollouts-app-prod-${{ vars.region }}
            namespace: argocd