apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: demo-auto-rollback
spec:
  args:
  - name: namespace
  metrics:
  - name: success-rate
    count: 5
    interval: 15s
    failureLimit: 2
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    # If there is no traffic to demo app during rollout we will have empty set.
    successCondition: len(result) == 0 || result[0] >= 0.95
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local
        query: |
          ( sum(rate(nginx_ingress_controller_requests{namespace="{{  args.namespace }}",status="200"}[30s])) + 1 )
          /
          ( sum(rate(nginx_ingress_controller_requests{namespace="{{  args.namespace }}"}[30s])) + 1 )
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: response-time
  namespace: demo-auto-rollback
spec:
  metrics:
  - name: response-time
    count: 5
    interval: 15s
    failureLimit: 2
    # NOTE: prometheus queries return results in the form of a vector.
    # So it is common to access the index 0 of the returned array to obtain the value
    # If there is no traffic to demo app during rollout we will have empty set.
    successCondition: len(result) == 0 || result[0] <= 1.5
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local
        query: |
          sum(rate(nginx_ingress_controller_response_duration_seconds_sum{namespace="{{  args.namespace }}",method="POST"}[30s]) or vector(.1)) 
          /
          sum(rate(nginx_ingress_controller_response_duration_seconds_count{namespace="{{  args.namespace }}",method="POST"}[30s])  or vector(.1))