apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: demo-auto-rollback
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: demo-auto-rollback
  namespace: demo-auto-rollback
spec:
  promotionPolicies:
  - stageSelector:
      name: "prod-amer-west"
    autoPromotionEnabled: true
    autoRollback: 
      onPromotion:
        - Failed
        - Errored
      onVerification:
        - Failed
        - Error
  - stageSelector:
      name: "prod-amer-east"
    autoPromotionEnabled: true
    autoRollback: 
      onPromotion:
        - Failed
        - Errored
      onVerification:
        - Failed
        - Error