apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo-auto-rollback
  namespace: demo-auto-rollback
spec:
  subscriptions:
  - image:
      repoURL: argoproj/rollouts-demo
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes: 
      - ^bad-red$
      - ^blue
      cacheByTag: true
      constraint: 
  - git:
      repoURL: https://github.com/akuity/sedemo-monorepo
      includePaths:
      - rollouts-app