apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique-prod
resources:
- ../../../kustomize/base/recommendationservice
images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  newTag: v0.10.5
