apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-ephemeral
  namespace: argocd
spec:
  description: Ephemeral PR preview environment demo
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
