apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-ephemeral-traditional
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: staging
      - env: prod
  template:
    metadata:
      name: demo-ephemeral-{{env}}
      annotations:
        kargo.akuity.io/authorized-stage: demo-ephemeral:{{env}}
    spec:
      project: demo-ephemeral
      source:
        repoURL: https://github.com/akuity/sedemo-platform
        targetRevision: main
        path: apps/demo-ephemeral/env/{{env}}
      destination:
        name: sedemo-primary
        namespace: demo-ephemeral-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
