apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-active
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev-east 
        env: dev-east
      - stage: dev-west 
        env: dev-west
      - stage: staging 
        env: staging-east
      - stage: staging 
        env: staging-west
      - stage: prod-east 
        env: prod-east
      - stage: prod-west 
        env: prod-west
  template:
    metadata:
      name: active-active-{{env}}
      annotations:
        kargo.akuity.io/authorized-stage: active-active:{{stage}}
        notifications.argoproj.io/subscriptions: |
          - trigger: [on-sync-succeeded, on-sync-running]
            destinations:
              - service: sedemo
                recipients: [argo-notifications]
    spec:
      project: rollouts
      source:
        repoURL: https://github.com/akuity/sedemo-monorepo
        path: active-active/deploy/targets/{{env}}
      destination:
        name: sedemo-primary
        namespace: active-active-{{env}}
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true