apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  description: Shared Kargo custom steps and cluster-level pipeline resources
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
