apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pokemon-verification
  namespace: team-emily-guestbook
spec:
  args:
  - name: pokemon
  metrics:
  - name: pokemon-xp
    interval: 5s
    count: 5
    successCondition: result < 200
    failureLimit: 3
    provider:
      web:
        url: https://pokeapi.co/api/v2/pokemon/{{args.pokemon}}
        jsonPath: "{$.base_experience}"
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: e2e-verification
  namespace: team-emily-guestbook
spec:
  metrics:
    - name: test
      interval: 5s
      count: 2
      failureLimit: 2
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - exit 1
                    image: alpine:latest
                    name: test
                restartPolicy: Never
