apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process
  namespace: guestbook
spec:
  vars:
  - name: app
  - name: imageRepo
  - name: gitRepo 
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
      - branch: stage/team-emily/${{ ctx.stage }}
        create: true
        path: ./out
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/${{ vars.app }}/base
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: kustomize-build
    config:
      path: ./src/${{ vars.app }}/stages/${{ ctx.stage }}
      outPath: ./out/manifests.yaml
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: | 
        ${{ ctx.stage }}: ${{ task.outputs['update-image'].commitMessage}}
  - uses: git-push
    config:
      path: ./out
      targetBranch: stage/team-emily/${{ ctx.stage }}
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.app }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitRepo }}