apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sedemo-kargo-bot-creds
  namespace: team-emily-guestbook
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sedemo-kargo-bot-creds              
    creationPolicy: Owner
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      stringData:
        githubAppClientID: "Iv23liGXe3GzMikgO3HA"
        githubAppInstallationID: "103319963"
        repoURL: "https://github.com/akuity/sedemo-platform"
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: sedemo-kargo-bot-pem
        property: sedemo-kargo-bot-pem