apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prometheus-verification
  namespace: demo-snow
spec:
  metrics:
  - name: success-rate
    interval: 15s
    successCondition: len(result) == 0 || result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: >
            (
            sum(rate(nginx_ingress_controller_requests{namespace="demo-dev",status="200",canary="demo-dev-rollouts-svc-canary-80"}[30s]))
            + 1 )

            /

            (
            sum(rate(nginx_ingress_controller_requests{namespace="demo-dev",canary="demo-dev-rollouts-svc-canary-80"}[30s]))
            + 1 )
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: e2e-verification
  namespace: demo-snow
spec:
  metrics:
    - name: test
      provider:
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                containers:
                  - command:
                      - /bin/sh
                      - -c
                      - exit 0
                    image: alpine:latest
                    name: test
                restartPolicy: Never
