apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gatekeeper-stage
  namespace: argocd
spec:
  description: Gatekeeper-Stage Kargo pattern demo
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
