apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-iac-coupled-prod
resources:
- ../../../kustomize/base
images:
- name: ghcr.io/akuity/demo-app-iac-coupled-app
  newTag: 1.4.2-cass7
