apiVersion: stable.example.com/v1beta
kind: BogusCustomResource
metadata:
  name: bogus-custom-resource
spec:
  spec:
    devices:
      requests:
      - name: single-gpu
        exactly:
          deviceClassName: gpu.nvidia.com
          allocationMode: ExactCount
          count: 1