apiVersion: batch/v1
kind: Job
metadata:
  name: kargo-sync-job-{{ .Values.application.name }}
  #annotations:    
  #  argocd.argoproj.io/hook: PostSync
  #  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kargo-sync
        image: "ghcr.io/akuity/sedemo-monorepo-kargo-cred-sync-job:latest"
        imagePullPolicy: Always
        env:
        - name: GITHUB_USER
          value: "eddiewebb"
        - name: GITHUB_ORG
          value: "akuity"
        - name: KARGO_PROJECT
          value: "{{ .Values.application.name }}"
        - name: KARGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kargo-admin-creds
              key: password
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: gh-image-creds
              key: password
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: kargo-admin-creds
              key: slack-token