apiVersion: batch/v1
kind: Job
metadata:
  name: kargo-sync-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Force=true