apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: user-inputs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: user-inputs
  namespace: user-inputs
spec: 
  promotionWindows:
  - name: us-offhours
    stageSelector:
      matchLabels:
        environment: prod
    kind: Allow
    rrule: FREQ=DAILY
    dtstart: TZID=America/New_York:20260101T220000
    dtend: TZID=America/New_York:20260102T040000