apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: user-inputs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: user-inputs
  namespace: user-inputs
spec: {}