# yaml-language-server: $schema=https://raw.githubusercontent.com/akuity/kargo/d30e01406b32d4ab5fa9445f5710b5011649d9ae/ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: user-inputs
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: some-warehouse
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: compose-output
        as: diff-link
        config:
          links:
            - icon: faDog
              label: See a long Doge
              tooltip: Can use variables like name of freight, ${{ ctx.targetFreight.name }}
              url: https://longdogechallenge.com/
            - icon: faGithub
              label: See a long Doge
              tooltip: Can use variables like name of freight, ${{ ctx.targetFreight.name }}
              url: https://longdogechallenge.com/
            - icon: dog
              label: See a long Doge
              tooltip: Can use variables like name of freight, ${{ ctx.targetFreight.name }}
              url: https://longdogechallenge.com/
      - task:
          name: require-release-note
      - uses: wait-for-approval
        as: approve
        config: {}            
      - uses: record-audit-event
        as: audit
        retry:
          errorThreshold: 3
        config:
          type: approved
          message: "Release to ${{ ctx.stage }} approved by ${{ outputs.approve.responses[0].user }}."
          actor: ${{ outputs.approve.responses[0].user }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: user-inputs
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: some-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: require-release-note
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: tofu
  namespace: user-inputs
  annotations:
    kargo.akuity.io/color: blue
spec:
  shard: sedemo-primary
  requestedFreight:
  - origin:
      kind: Warehouse
      name: some-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: tofu-task
        config:
          cmd: colors
      - uses: tofu-task
        config:
          cmd: cp /workspace/*.tf . && tofu plan


