apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: tofu-task
spec:
  image: ghcr.io/akuity/sedemo-platform-tasks:tofu
  command: [ "sh","-c", "${{ config.cmd}}" ]
  output:
    source:
      type: Stdout
      format: Text