apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gatekeeper-stage
  namespace: gatekeeper-stage
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/akuity/sedemo-monorepo
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      includePaths:
      - gatekeeper-app
  - image:
      repoURL: ghcr.io/akuity/sedemo-monorepo-gatekeeper-app
      discoveryLimit: 20
      imageSelectionStrategy: NewestBuild
      allowTagsRegexes:
      - ^[0-9a-f]{40}$
