apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-snow
  namespace: argocd
spec:
  generators:
    - matrix: 
        generators: 
          - list:
              elements:
                - stage: dev
                - stage: staging 
                - stage: prod-amer-east
                - stage: prod-amer-west
                - stage: prod-emea
          - list: 
              elements: 
                - component: frontend 
                - component: backend
  template:
    metadata:
      name: demo-snow-{{stage}}-{{component}} 
      labels: 
        app.kubernetes.io/part-of: demo-snow
        kargo.akuity.io/stage: "{{stage}}"
        app.kubernetes.io/component: "{{component}}"
      annotations:
        kargo.akuity.io/authorized-stage: demo-snow:{{stage}}
        notifications.argoproj.io/subscriptions: |
          - trigger: [on-sync-succeeded, on-sync-running]
            destinations:
              - service: sedemo
                recipients: [argo-notifications]
    spec:
      project: demo-snow
      source:
        repoURL: https://github.com/akuity/sedemo-monorepo
        targetRevision: env-snow-demo/{{stage}}
        path: "{{component}}"
      destination:
        name: sedemo-primary
        namespace: snow-demo-{{stage}}-{{component}}
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
