apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-snow
  namespace: argocd
spec:
  description: ServiceNow change management integration demo
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
