apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: deploy-backend
  namespace: kargo-microservices
spec:
  vars:
  - name: env
  - name: reg
    value: us-central1-docker.pkg.dev/google-samples/microservices-demo
  - name: gitRepo
    value: https://github.com/akuity/sedemo-platform.git
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
  - uses: kustomize-set-image
    as: update-images
    config:
      path: ./src/apps/demo-microservices/env/${{ vars.env }}/backend
      images:
      - image: ${{ vars.reg }}/cartservice
        tag: ${{ imageFrom(vars.reg + "/cartservice").Tag }}
      - image: ${{ vars.reg }}/checkoutservice
        tag: ${{ imageFrom(vars.reg + "/checkoutservice").Tag }}
      - image: ${{ vars.reg }}/currencyservice
        tag: ${{ imageFrom(vars.reg + "/currencyservice").Tag }}
      - image: ${{ vars.reg }}/emailservice
        tag: ${{ imageFrom(vars.reg + "/emailservice").Tag }}
      - image: ${{ vars.reg }}/paymentservice
        tag: ${{ imageFrom(vars.reg + "/paymentservice").Tag }}
      - image: ${{ vars.reg }}/productcatalogservice
        tag: ${{ imageFrom(vars.reg + "/productcatalogservice").Tag }}
      - image: ${{ vars.reg }}/shippingservice
        tag: ${{ imageFrom(vars.reg + "/shippingservice").Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: "backend-${{ vars.env }}: promote ${{ ctx.targetFreight.origin.name }}"
  - uses: git-push
    config:
      path: ./src
      targetBranch: main
  - uses: argocd-update
    config:
      apps:
      - name: backend-${{ vars.env }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: deploy-frontend-service
  namespace: kargo-microservices
spec:
  vars:
  - name: env
  - name: service
  - name: reg
    value: us-central1-docker.pkg.dev/google-samples/microservices-demo
  - name: gitRepo
    value: https://github.com/akuity/sedemo-platform.git
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
  - uses: kustomize-set-image
    config:
      path: ./src/apps/demo-microservices/env/${{ vars.env }}/${{ vars.service }}
      images:
      - image: ${{ vars.reg }}/${{ vars.service }}
        tag: ${{ imageFrom(vars.reg + "/" + vars.service).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: "${{ vars.service }}-${{ vars.env }}: promote ${{ ctx.targetFreight.origin.name }}"
  - uses: git-push
    config:
      path: ./src
      targetBranch: main
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.service }}-${{ vars.env }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: deploy-loadgenerator
  namespace: kargo-microservices
spec:
  vars:
  - name: env
  - name: reg
    value: us-central1-docker.pkg.dev/google-samples/microservices-demo
  - name: gitRepo
    value: https://github.com/akuity/sedemo-platform.git
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
  - uses: kustomize-set-image
    as: update-images
    config:
      path: ./src/apps/demo-microservices/env/${{ vars.env }}/loadgenerator
      images:
      - image: ${{ vars.reg }}/loadgenerator
        tag: ${{ imageFrom(vars.reg + "/loadgenerator").Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: "loadgenerator-${{ vars.env }}: promote ${{ ctx.targetFreight.origin.name }}"
  - uses: git-push
    config:
      path: ./src
      targetBranch: main
  - uses: argocd-update
    config:
      apps:
      - name: loadgenerator-${{ vars.env }}
