apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-dev
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: backend-group
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-backend
        vars:
        - name: env
          value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-prod
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: backend-group
    sources:
      stages:
      - backend-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-backend
        vars:
        - name: env
          value: prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-dev
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: frontend-group
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-frontend
        vars:
        - name: env
          value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: frontend-prod
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: frontend-group
    sources:
      stages:
      - frontend-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-frontend
        vars:
        - name: env
          value: prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: loadgen-dev
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: loadgenerator
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-loadgenerator
        vars:
        - name: env
          value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: loadgen-prod
  namespace: kargo-microservices
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: loadgenerator
    sources:
      stages:
      - loadgen-dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: deploy-loadgenerator
        vars:
        - name: env
          value: prod
