apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: utilities
  namespace: argocd
spec:
  description: Non-Demo components used to aid demo environment.
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
