apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: intelligence-demo
  namespace: argocd
spec:
  description: Intelligence Demo with OOM and Crashloop scenarios
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
