image:
  repository: ghcr.io/akuity/guestbook
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

useRollout: false

featureFlags: {}
  # FEATURE_FOO: enabled

service:
  type: ClusterIP
  port: 80
