apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app-iac-coupled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-iac-coupled
  template:
    metadata:
      labels:
        app: app-iac-coupled
    spec:
      containers:
      - name: app
        image: ghcr.io/akuity/sedemo-monorepo-rollouts-app
        ports:
        - containerPort: 8080
