apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-boutique-dev
resources:
- ../../../kustomize/base/adservice
images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  newTag: v0.10.1
