apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: fargate-task-def
  namespace: beyond-k8s
  annotations:
    kargo.akuity.io/color: gray
spec:
  shard: sedemo-primary
  vars:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-fargate

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: beyond-k8s
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/argocd-context: '[{"name":"beyond-k8s-dev","namespace":"argocd"}]'
spec:
  shard: sedemo-primary
  vars:
  - name: argocdApp
    value: beyond-k8s-dev
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app
    sources:
      stages:
      - fargate-task-def
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-b
  namespace: beyond-k8s
  annotations:
    kargo.akuity.io/color: amber
    kargo.akuity.io/argocd-context: '[{"name":"beyond-k8s-staging-b","namespace":"argocd"}]'
spec:
  shard: sedemo-primary
  vars:
  - name: argocdApp
    value: beyond-k8s-staging-b
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging-a
  namespace: beyond-k8s
  annotations:
    kargo.akuity.io/color: amber
    kargo.akuity.io/argocd-context: '[{"name":"beyond-k8s-staging-a","namespace":"argocd"}]'
spec:
  shard: sedemo-primary
  vars:
  - name: argocdApp
    value: beyond-k8s-staging-a
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: beyond-k8s
  annotations:
    kargo.akuity.io/color: violet
    kargo.akuity.io/argocd-context: '[{"name":"beyond-k8s-prod","namespace":"argocd"}]'
spec:
  shard: sedemo-primary
  vars:
  - name: argocdApp
    value: beyond-k8s-prod
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app
    sources:
      stages:
      - staging-a
      - staging-b
  promotionTemplate:
    spec:
      steps:
      - task:
          name: pr-promote