apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-fargate
  namespace: beyond-k8s
spec:
  vars:
  - name: repoURL
    value: https://github.com/akuity/sedemo-monorepo
  - name: fargate
    value: ghcr.io/akuity/sedemo-monorepo-fargate-app
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: main
        path: ./tasks
      - commit: ${{ commitFrom( vars.repoURL ).ID }}
        path: ./template
  - uses: copy
    config:
      inPath: ./template/beyond-k8s/fargate/task.json
      outPath: ./tasks/beyond-k8s/env/fargate-tasks/task-${{ imageFrom(vars.fargate).Tag }}.json
  - uses: json-update
    as: update-fargate-tag
    config:
      path: ./tasks/beyond-k8s/env/fargate-tasks/task-${{ imageFrom(vars.fargate).Tag }}.json
      updates:
      - key: containerDefinitions.0.image
        value: ${{ vars.fargate }}:${{ imageFrom(vars.fargate).Tag }}
  - uses: fargate-promote
    config:
      env:
      - name: AWS_REGION
        value: us-west-2
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: AWS_SECRET_ACCESS_KEY
  - uses: git-commit
    config:
      path: ./tasks
      message: |
        Update ${{ ctx.stage }} to ${{ ctx.targetFreight.name }}

        Fargate: ${{ vars.fargate }}:${{ imageFrom(vars.fargate).Tag }}
  - uses: git-push
    config:
      path: ./tasks

 