apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: fargate
  namespace: beyond-k8s
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/akuity/sedemo-monorepo-fargate-app
      imageSelectionStrategy: SemVer