apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: oci-airgap
  namespace: argocd
spec:
  description: OCI Airgap demo — GitOps promotion via ORAS OCI artifacts
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
