apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: app
  namespace: beyond-k8s
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/akuity/guestbook
      imageSelectionStrategy: SemVer
  - git:
      repoURL: https://github.com/akuity/sedemo-monorepo
      includePaths:
      - beyond-k8s/config
  - image:
      repoURL: ghcr.io/akuity/sedemo-monorepo-beyond-k8s-lambda
      imageSelectionStrategy: SemVer