# =============================================================================
# RINGED DEPLOYMENT VERIFICATION TEMPLATES
# =============================================================================
# Analysis templates using the PokeAPI for demonstrating verification gates
# between deployment rings. Each ring uses a different Pokemon to verify.
# =============================================================================

---
# RING 0 - Canary Health Check (Pikachu)
# Fast validation for canary deployments
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ring-health-check
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  args:
  - name: ring
  - name: threshold
  metrics:
  - name: pokemon-health
    interval: 5s
    count: 3
    successCondition: result < 120
    failureLimit: 1
    provider:
      web:
        url: https://pokeapi.co/api/v2/pokemon/pikachu
        jsonPath: "{$.base_experience}"

---
# RING 1 - Early Adopter Success Rate (Charizard)
# Validates early adopter ring is healthy
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ring-success-rate
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  args:
  - name: ring
  - name: min-success-rate
  metrics:
  - name: pokemon-success
    interval: 5s
    count: 3
    successCondition: result < 300
    failureLimit: 1
    provider:
      web:
        url: https://pokeapi.co/api/v2/pokemon/charizard
        jsonPath: "{$.base_experience}"

---
# RING 2 - Regional Health (Bulbasaur)
# Validates regional deployments before global rollout
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ring-regional-health
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  args:
  - name: region
  metrics:
  - name: pokemon-regional
    interval: 5s
    count: 3
    successCondition: result < 100
    failureLimit: 1
    provider:
      web:
        url: https://pokeapi.co/api/v2/pokemon/bulbasaur
        jsonPath: "{$.base_experience}"
