# =============================================================================
# RINGED DEPLOYMENT STRATEGY - team-daniel
# =============================================================================
# Pipeline visualization:
#
#                                         ┌─→ ring-2-useast ─┐
#   Warehouse → ring-0-canary → ring-1-early                  ├→ ring-3-global
#                                         └─→ ring-2-euwest ─┘
#
# Ring 0: Canary/Internal - immediate feedback, auto-promoted
# Ring 1: Early Adopters - ~5% traffic, auto-promoted after verification
# Ring 2: Regional Expansion - parallel regional rollout, manual approval
# Ring 3: Global Production - full rollout after all regions verified
# =============================================================================

---
# RING 0 - CANARY
# First line of defense, internal testing, immediate feedback loop
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-0-canary
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: gray
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-standard
  verification:
    analysisTemplates:
    - name: ring-health-check
    args:
    - name: ring
      value: "0"
    - name: threshold
      value: "95"

---
# RING 1 - EARLY ADOPTERS
# Small percentage of production traffic, validates with real users
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-1-early
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - ring-0-canary
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-standard
  verification:
    analysisTemplates:
    - name: ring-success-rate
    args:
    - name: ring
      value: "1"
    - name: min-success-rate
      value: "99"

---
# RING 2 - REGIONAL EXPANSION (US EAST)
# First regional production deployment
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-2-useast
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: cyan
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - ring-1-early
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-standard
  verification:
    analysisTemplates:
    - name: ring-regional-health
    args:
    - name: region
      value: "us-east"

---
# RING 2 - REGIONAL EXPANSION (EU WEST)
# Parallel regional deployment with US East
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-2-euwest
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: cyan
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - ring-1-early
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-standard
  verification:
    analysisTemplates:
    - name: ring-regional-health
    args:
    - name: region
      value: "eu-west"

---
# RING 3 - GLOBAL PRODUCTION
# Final stage - requires both Ring 2 regions to be verified
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-3-global
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - ring-2-useast
      - ring-2-euwest
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote-standard
