apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oom-demo-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: oom-demo:dev
spec:
  project: default
  source:
    repoURL: https://github.com/akuity/sedemo-app-monorepo
    path: oom/manifest
    targetRevision: env/dev
  destination:
        server: http://cluster-eddie-local:8001
        namespace: oom-demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
