apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: demo-intelligence
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/akuity/guestbook
