#
# Notes: This secret is managed by ESO
# This secret is local to a specific project,but global credentials are possible.
#     https://docs.kargo.io/operator-guide/security/managing-credentials#enabling-global-credentials

apiVersion: v1
kind: ExternalSecret
metadata:
  name: gh-repo-creds
  namespace: rollouts-app-remote
  labels:
    kargo.akuity.io/cred-type: git
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
    namespace: default
  target:
    name: gh-repo-creds
  data:
  - secretKey: secret-key-name
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat


---
# apiVersion: v1
# kind: ExternalSecret
# metadata:
#   name: gh-image-creds
#   namespace: rollouts-app-remote
#   labels:
#     kargo.akuity.io/cred-type: image
# stringData:
#   repoURL: ghcr.io/eddiewebb/rollouts
#   username: eddiewebb
#   password: muchy

---
