apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-secret-store-kargo
  namespace: argocd
spec:
  project: kargo
  source:
    repoURL: https://github.com/akuity/sedemo-platform
    path: secrets
    targetRevision: main
  destination:
        name: sedemo-primary
        namespace: rollouts-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
