# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-ada-postgresql
  namespace: team-ada-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: team-ada-postgresql
  data:
  - secretKey: postgres-password
    remoteRef:
      key: team-ada-akkoma-prod-postgresql
      property: postgres-password
