apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-eddie
  namespace: argocd
spec:
  generators:
  - matrix:
     generators:
      - list:
          elements:
            - stage: dev
            - stage: staging
      - list:
          elements:
            - cluster: sedemo-primary
              name: cluster-a
            - cluster: sedemo-secondary
              name: cluster-b
  template:
    metadata:
      name: team-eddie-{{stage}}-{{name}}
      annotations:
        kargo.akuity.io/authorized-stage: team-eddie:{{stage}}-primary,team-eddie:{{stage}}-secondary
    spec:
      project: team-eddie
      source:
        repoURL: https://github.com/akuity/sedemo-monorepo
        targetRevision: env-eddie/{{stage}}/{{name}}
        path: .
      destination:
        name: '{{cluster}}'
        namespace: team-eddie-{{stage}}
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true