---
# Source: deploy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rollouts-svc-stable
  annotations:
    prometheus.io/fastscrape: 'true'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rollouts-app
---
# Source: deploy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: rollouts-app
  template:
    metadata:
      labels:
        app: rollouts-app
    spec:
      containers:
        - image: "ghcr.io/akuity/sedemo-monorepo-snow-demo:49-green"
          name: rollouts-app
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              value: "49-green"
            - name: STAGE
              value: prod-emea
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
# Source: deploy/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "snow-demo-prod-emea.akpdemoapps.link"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: rollouts-svc-stable
            port:
              number: 80
