# THis file is referenced by the apps-seed-argo.yaml to bootstrap Argo CD
# It will pull the specific applications from the git repo to be managed by Argo CD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: default
  source:   
    repoURL:  https://github.com/eddiewebb/argodemo-platform
    path: apps/rollouts-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      enabled: true