
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-rollouts-definition
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eddiewebb/argodemo-platform
    path: kargo
    directory:
      recurse: true
  destination:
    name: kargo
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
