---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: gray
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: config-dev
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/akuity/sedemo-platform
          checkout:
          - branch: main
            path: ./src
      - uses: opa-test
        config:
          path: ./src/apps/team-daniel/charts/guestbook/templates/deployment.yaml
      - task:
          name: promote-guestbook
      - uses: teams-notify
        config:
          webhookURL: ${{ secret("teams-webhook")["teams-webhook"] }}
          title: "Promoted to ${{ ctx.stage }}"
          message: "guestbook ${{ imageFrom('ghcr.io/akuity/guestbook').Tag }} is live"
          stage: ${{ ctx.stage }}
          freight: ${{ ctx.targetFreight.name }}

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-prod","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: features
    sources:
      stages:
      - dev
  - origin:
      kind: Warehouse
      name: config-prod
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/akuity/sedemo-platform
          checkout:
          - branch: main
            path: ./src
      - uses: gha-dispatch-workflow
        as: gha-dispatch
        config:
          repoURL: https://github.com/akuity/sedemo-platform
          workflowFile: example-github-action.yaml
          ref: main
          inputs:
            environment: ${{ ctx.stage }}
            version: ${{ imageFrom('ghcr.io/akuity/guestbook').Tag }}
      - uses: gha-wait-for-workflow
        config:
          repoURL: https://github.com/akuity/sedemo-platform
          runID: ${{ outputs['gha-dispatch'].runID }}
          expectedConclusion: success
      - uses: opa-test
        config:
          path: ./src/apps/team-daniel/charts/guestbook/templates/deployment.yaml
      - uses: trivy-image
        config:
          image: ghcr.io/akuity/guestbook:${{ imageFrom('ghcr.io/akuity/guestbook').Tag }}
      - task:
          name: promote-guestbook
