apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-guestbook
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  vars:
  - name: gitRepo
    value: https://github.com/akuity/sedemo-platform
  - name: imageRepo
    value: ghcr.io/akuity/guestbook
  steps:
  - if: ${{ ctx.targetFreight.origin.name != "config-dev" && ctx.targetFreight.origin.name != "config-prod" }}
    uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./out
  - if: ${{ ctx.targetFreight.origin.name == "guestbook" }}
    uses: yaml-update
    as: update-image
    config:
      path: ./out/apps/team-daniel/env/${{ ctx.stage }}/image.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom(vars.imageRepo).Tag }}
  - if: ${{ ctx.targetFreight.origin.name == "features" }}
    uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - commit: '${{ commitFrom(vars.gitRepo, {"kind": "Warehouse", "name": "features"}).ID }}'
        path: ./features
  - if: ${{ ctx.targetFreight.origin.name == "features" }}
    uses: copy
    config:
      inPath: ./features/apps/team-daniel/base/feature-flags.yaml
      outPath: ./out/apps/team-daniel/env/${{ ctx.stage }}/feature-flags.yaml
  - if: ${{ ctx.targetFreight.origin.name != "config-dev" && ctx.targetFreight.origin.name != "config-prod" }}
    uses: git-commit
    config:
      path: ./out
      message: "${{
        ctx.targetFreight.origin.name == 'guestbook' ?
        ctx.stage + ': deploy guestbook ' + imageFrom(vars.imageRepo).Tag :
        ctx.stage + ': update feature flags from ' + commitFrom(vars.gitRepo, {"kind": "Warehouse", "name": "features"}).ID
        }}"
  - if: ${{ ctx.targetFreight.origin.name != "config-dev" && ctx.targetFreight.origin.name != "config-prod" }}
    uses: git-push
    config:
      path: ./out
      targetBranch: main
  - uses: argocd-update
    config:
      apps:
      - name: team-daniel-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitRepo }}
