apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-guestbook
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  vars:
  - name: gitRepo
    value: https://github.com/akuity/sedemo-platform
  - name: imageRepo
    value: ghcr.io/akuity/guestbook
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./out
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/apps/team-daniel/env/${{ ctx.stage }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: git-commit
    config:
      path: ./out
      message: "${{ ctx.stage }}: deploy guestbook ${{ imageFrom(vars.imageRepo).Tag }}"
  - uses: git-push
    config:
      path: ./out
      targetBranch: main
  - uses: argocd-update
    config:
      apps:
      - name: team-daniel-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.gitRepo }}
