apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: templated-team-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/akuity/sedemo-monorepo
        revision: main
        directories:
        - path: templated/*
  template:
    metadata:
      name: '{{.path.basename}}-apps-definition'
      namespace: argocd
    spec:
      #project: '{{.path.basename}}'
      project: templated-apps
      sources:
      #pull custom values from team managed monorepo folder
      - repoURL: https://github.com/akuity/sedemo-monorepo.git
        targetRevision: main
        ref: appValues 
      # apply to platform team managed kargo templates
      - targetRevision: HEAD
        repoURL: https://github.com/akuity/sedemo-platform
        path: templated_teams/apps-helm/
        helm:
          valueFiles:
          - $appValues/templated/{{.path.basename}}/platform/app-values.yaml
      destination:
        name: sedemo-primary
      syncPolicy:
        automated:
          prune: true
          enabled: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true