apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: templated-team-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/akuity/sedemo-monorepo
              revision: main
              directories:
              - path: templated/*
          - list:
              elements:
              - stage: dev
              - stage: staging 
              - stage: prod
  template:
    metadata:
      name: '{{.path.basename}}-{{.stage}}'
      namespace: argocd
      annotations:
        kargo.akuity.io/authorized-stage: '{{.path.basename}}:{{.stage}}'
    spec:
      #project: '{{.path.basename}}'
      project: templated-apps
      source:
        repoURL: https://github.com/akuity/sedemo-monorepo
        targetRevision: env/{{.path.basename}}-{{.stage}}
        path: .
      destination:
        name: sedemo-primary
        namespace: '{{.path.basename}}-{{.stage}}'
      syncPolicy:
        automated:
          prune: true
          enabled: true
          #selfHeal: true
        syncOptions:
        - CreateNamespace=true