apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 27.41.2
    helm:
      releaseName: prometheus
      # valuesObject:
      #   server:
      #     ingress:
      #       enabled: true
      #       ingressClassName: nginx
      #       path: /
      #       hosts:
      #       - prometheus.prometheus.k8s.orb.local
      valuesFiles:
      - "$localValues/value-overrides/prometheus-values.yaml"
  - repoURL: https://github.com/akuity/sedemo-platform.git
    targetRevision: main
    ref: localValues 
    directory:
      recurse: true
  destination:
        server: http://cluster-eddie-local:8001
        namespace: prometheus
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
