apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-ephemeral-staging
resources:
- ../base
images:
- name: ghcr.io/akuity/sedemo-monorepo-rollouts-app
  newTag: latest
patches:
- patch: |-
    - op: replace
      path: /data/environment
      value: staging
  target:
    kind: ConfigMap
    name: app-config
