apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: local-shard-eso
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: local-shard-eso
  namespace: local-shard-eso
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: "regex:prod.*"
    autoPromotionEnabled: true