---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-developer
  namespace: {{ .Values.projectName }}
  annotations:
    kargo.akuity.io/description: Permissions to promote into dev.
    rbac.kargo.akuity.io/claims: '{"groups":["developer"]}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-developer
  namespace: {{ .Values.projectName }}
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - promotions
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - kargo.akuity.io
  resources:
  - stages
  verbs:
  - promote
  # Limit promotions to a subset of Stages
  resourceNames:
  - dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-developer
  namespace: {{ .Values.projectName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-developer
subjects:
- kind: ServiceAccount
  name: app-developer
  namespace: {{ .Values.projectName }}
---
# This RoleBinding allows the app-developer ServiceAccount to view project
# resources (without redefining read rules), by binding it to the
# built-in kargo-viewer Role.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-developer-viewer
  namespace: {{ .Values.projectName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-viewer
subjects:
- kind: ServiceAccount
  name: app-developer
  namespace: {{ .Values.projectName }}