kind: EventRouter
apiVersion: ee.kargo.akuity.io/v1alpha1
metadata:
  name: promotion-status
  namespace: {{ .Values.application.name }}
spec:
  types:
    - PromotionFailed
    - PromotionErrored
    - PromotionSucceeded
    - PromotionCreated
  channels:
    - name: kargo-notifications
      kind: ClusterMessageChannel