apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ .Values.application.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.name }}
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true