apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ .Values.projectName }}
  namespace: {{ .Values.projectName }}
spec:
  subscriptions:
  - image:
      repoURL: {{ .Values.image.repository }}
      discoveryLimit: 5
      imageSelectionStrategy: NewestBuild
      allowTags: ^\d*-[a-z]*$
  - git:
      repoURL: {{ .Values.repoUrl }}
      includePaths:
      - {{ .Values.projectPath }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: '{{ .Values.projectName }}-chart'
  namespace: {{ .Values.projectName }}
spec:
  subscriptions:
  - git:
      repoURL: {{ .Values.chartUrl }}
      includePaths:
      - {{ .Values.chartPath }}