apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: red
  name: dev
  namespace: many-argocds
spec:
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: ${{ vars.sourceBranch }}
                path: ${{ vars.path_src }}
            repoURL: ${{ vars.gitRepo }}
          uses: git-clone
        - uses: yaml-update
          config:
            path: ./src/akuity.yaml
            updates:
            - key: value
              value: ${{ ctx.promotion }}
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.path_src }}
            message: "Writecommitfor ${{ ctx.promotion }}"
            author:
              #your-app-name[bot]
              name: akuity-signing-demo[bot]
              #your-app-id+your-app-name[bot]@users.noreply.github.com
              email: "261204081+akuity-signing-demo@users.noreply.github.com"
        - uses: git-push
          as: push
          config:
            path: ${{ vars.path_src }}
      vars:
        - name: gitRepo
          value: https://github.com/eddiewebb/circleci-samples
        - name: sourceBranch
          value: main
        - name: path_src
          value: ./src
  requestedFreight:
    - origin:
        kind: Warehouse
        name: many-argocds
      sources:
        direct: true

