# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team-ada-app-secrets
  namespace: team-ada-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: team-ada-app-secrets
  data:
  - secretKey: secret-key-base
    remoteRef:
      key: team-ada-akkoma-dev-app
      property: secret-key-base
  - secretKey: signing-salt
    remoteRef:
      key: team-ada-akkoma-dev-app
      property: signing-salt
  - secretKey: release-cookie
    remoteRef:
      key: team-ada-akkoma-dev-app
      property: release-cookie
