apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-microservices
  namespace: argocd
spec:
  description: Microservices Demo with lots of apps
  sourceRepos:
    - '*'
  destinations:
    - server: '*'
      name: '*'
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
