
# allow SCM Generator to talk to GitHub repos
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-set-secret
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: application-set-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: scm-creds
          akuity.io/secret-sync: "true"
          team: templated-teams
      data: 
        token: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# allow dynamically created repos in Akuity org to be cloned
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token-repos
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-token-repos
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
          akuity.io/secret-sync: "true"
          team: templated-teams
      data: 
        type: git
        url: https://github.com/akuity/
        username: eddiewebb
        password: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
