apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      # Role created by IAC Repo allows role assumption from EKS pods
      role: arn:aws:iam::218691292270:role/sedemo-secrets-access-from-eks
      region: us-west-2