# Need ns where kargo will look for project assets, including secrets.
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-secrets-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: kargo-controller
  namespace: akuity
---
# JIRA access from kargo promotion
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jira-access-secret
  namespace: kargo-secrets-namespace
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jira-access-secret
  data:
  - secretKey: domain
    remoteRef:
      key: kargo-jira-access
      property: domain
  - secretKey: username
    remoteRef:
      key: kargo-jira-access
      property: username
  - secretKey: password
    remoteRef:
      key: kargo-jira-access
      property: password
---
# secret runs on EKS cluster. in project scoped NS
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-repo-creds
  namespace: kargo-secrets-namespace
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-repo-creds
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data: 
        repoURL: https://github.com/akuity/sedemo-rollouts-app
        username: eddiewebb
        password: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# secret runs on EKS cluster. in project scoped NS
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-image-creds
  namespace: kargo-secrets-namespace
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-image-creds
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
      data: 
        repoURL: ghcr.io/akuity/
        username: eddiewebb
        password: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# allow SCM Generator to talk to GitHub repos
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: application-set-secret
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: application-set-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: scm-creds
          akuity.io/secret-sync: "true"
          team: templated-teams
      data: 
        token: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# allow dynamically created repos in Akuity org to be cloned
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token-repos
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: github-token-repos
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
          akuity.io/secret-sync: "true"
          team: templated-teams
      data: 
        type: git
        url: https://github.com/akuity/
        username: eddiewebb
        password: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# github app things
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sedemo-kargo-bot-creds
  namespace: kargo-secrets-namespace
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sedemo-kargo-bot-creds              
    creationPolicy: Owner
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      stringData:
        githubAppClientID: "Iv23liGXe3GzMikgO3HA"
        githubAppInstallationID: "103319963"
        repoURL: "https://github.com/akuity/sedemo-platform"
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: sedemo-kargo-bot-pem
        property: sedemo-kargo-bot-pem
