# SLACK TOKEN - secret created by ESO, pushed into system resources in kargo
# Currently does not work, issue syncing to kargo-system-resources
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: akuity
  labels:
    kargo.akuity.io/secret-sync: kargo-system-resources
    kargo.akuity.io/cred-type: generic
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: slack-token
  data:
  - secretKey: apiKey
    remoteRef:
      key: kargo-admin-password
      property: slack-token
---
# JIRA access from kargo promotion - pushed to SHARED ns, allows use by all projects
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jira-access-secret
  namespace: akuity
  labels:
    kargo.akuity.io/secret-sync: kargo-shared-resources
    kargo.akuity.io/cred-type: generic
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: jira-access-secret
  data:
  - secretKey: domain
    remoteRef:
      key: kargo-jira-access
      property: domain
  - secretKey: username
    remoteRef:
      key: kargo-jira-access
      property: username
  - secretKey: password
    remoteRef:
      key: kargo-jira-access
      property: password
---
# Git REPO CREDS - secret runs on EKS cluster. Shared by all projects
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-repo-creds
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-repo-creds
    template:
      metadata:
        labels:
          kargo.akuity.io/secret-sync: kargo-shared-resources
          kargo.akuity.io/cred-type: git
      engineVersion: v2
      data: 
        repoURL: https://github.com/akuity
        username: eddiewebb
        password: "{{.pat}}"
        repoURLIsRegex: true
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# GHCR (image) secret runs on EKS cluster. Shared by all projects
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-image-creds
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-image-creds
    template: 
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/secret-sync: kargo-shared-resources
          kargo.akuity.io/cred-type: image
      data: 
        repoURL: ghcr.io/akuity/
        username: eddiewebb
        password: "{{.pat}}"
  data:
  - secretKey: pat
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# github app things
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sedemo-kargo-bot-creds
  namespace: akuity
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sedemo-kargo-bot-creds              
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
          kargo.akuity.io/secret-sync: team-emily-guestbook
      data:
        githubAppClientID: "Iv23liGXe3GzMikgO3HA"
        githubAppInstallationID: "103319963"
        repoURL: "https://github.com/akuity/sedemo-platform"
        githubAppPrivateKey: "{{.pem}}"
  data:
    - secretKey: pem
      remoteRef:
        key: sedemo-kargo-bot-pem
        property: sedemo-kargo-bot-pem
