# secret created by ESO, pushed into app specific namespace for use by kargo cred job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-creds
  namespace: kargo-sync-jobs
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kargo-admin-creds
  data:
  - secretKey: password
    remoteRef:
      key: kargo-admin-password
      property: password
  - secretKey: slack-token
    remoteRef:
      key: kargo-admin-password
      property: slack-token
---
# secret created by ESO, pushed into app specific namespace for use by kargo cred job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-image-creds
  namespace: kargo-sync-jobs
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-image-creds
  data:
  - secretKey: password
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
---
# secret created by ESO, pushed into app specific namespace for use by kargo cred job
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-creds
  namespace: akuity
spec:
  refreshInterval: 24h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kargo-admin-creds
    metadata:
      labels:
        app.kubernetes.io/managed-by: external-secrets
        kargo.akuity.io/secret-sync: kargo-cluster-secrets
        kargo.akuity.io/cred-type: generic
  data:
  - secretKey: apiKey
    remoteRef:
      key: kargo-admin-password
      property: slack-token
---