# Need ns where kargo will look for project assets, including secrets.
apiVersion: v1
kind: Namespace
metadata:
  name: rollouts-app-remote
---
# secret runs on EKS cluster. in project scoped NS
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-repo-creds
  namespace: rollouts-app-remote
spec:
  refreshInterval: 1h # How often to refresh the secret from AWS Secrets Manager
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gh-repo-creds
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        stringData: |
          repoURL: https://github.com/eddiewebb/argodemo-rollouts-app
          username: eddiewebb
          password: {{.kargo-pats}}

  data:
  - secretKey: password
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat
