# Need ns where kargo will look for project assets, including secrets.
apiVersion: v1
kind: Namespace
metadata:
  name: rollouts-app-remote
---
# secret runs on EKS cluster. in project scoped NS
apiVersion: v1
kind: ExternalSecret
metadata:
  name: gh-repo-creds
  namespace: rollouts-app-remote
  labels:
    kargo.akuity.io/cred-type: git
spec:
  # our actual secret store is in EKS cluster default NS
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
    namespace: default
  target:
    name: gh-repo-creds
  data:
  - secretKey: secret-key-name
    remoteRef:
      key: kargo-pats
      property: eddies-gh-pat

