apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: "{{ .Values.projectName }}-app"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: "{{ .Values.projectName }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.projectName }}-app"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: "{{ .Values.projectName }}-app"
          ports:
            - containerPort: 8080
          env:
            - name: SEMVER
              value: "{{.Values.image.tag}}"
            - name: STAGE
              value: {{.Values.kargo.stage}}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      canaryService: svc-canary  # required
      stableService: svc-stable # required
      trafficRouting:
        nginx:
          stableIngress: stable-ingress
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 4
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 20s 
        - setWeight: 20
        - analysis:
            templates:
            - templateName: loadgen
        - pause:
            duration: 20s 
        - setWeight: 50
        - pause:
            duration: 1m 
        - setWeight: 75
        - pause:
            duration: 20s 
        - setWeight: 100